function substNitroza() {
    var sNitroza = document.getElementById("substContent");
    sNitroza.innerHTML = "<p></p><h3>Nitroza (88/12, 51/40/9, 50/50)</h3><p><details><summary>Zwroty bezpieczeństwa:</summary><p>Met. Corr. 1; H290 - powoduje korozję metali</p><p>Skin Corr. 1A; H314 - powoduje powazne oparzenia skóry i uszkodzenie oczu</p><p>Ox. Liq. 3; H272 - substancja ciekła utleniająca</p></details><hr></p><p><details><summary>Klasyfikacja ZDR/ZZR:</summary><p>50 / 200 t (H272)</p></details></p><hr><p><details><summary>CAS:</summary><p>51602-38-1</p></details><hr><details><summary>Palność:</summary><p>Substancja niepalna</p></details>"; 
}

function substKas() {
    var sKas = document.getElementById("substContent");
    sKas.innerHTML = "<p></p><h3>Kwas azotowy stężony (98%)</h3><details><summary>Zwroty bezpieczeństwa:</summary><p>Ox. Liq. 3; H272 - substancja ciekła utleniająca</p><p>Skin Corr. 1A; H314 - powoduje powazne oparzenia skóry i uszkodzenie oczu</p><p>Met. Corr. 1; H290 - powoduje korozję metali</p></details><hr></p><p><details><summary>Klasyfikacja ZDR/ZZR:</summary><p>50 / 200 t (H272)</p></details></p><hr><p><details><summary>CAS:</summary><p>7697-37-2</p></details><hr><details><summary>Palność:</summary><p>Substancja niepalna</p></details>";
}

function substOleum() {
    var sOleum = document.getElementById("substContent");
    sOleum.innerHTML = "<p></p><h3>Oleum (25%)</h3><details><summary>Zwroty bezpieczeństwa:</summary><p>Skin Corr. 1A; H314 - powoduje powazne oparzenia skóry i uszkodzenie oczu</p><p>STOT SE 3; H335 - może powodować podrażnienie dróg oddechowych</p><p>EUH014 - reaguje gwałtownie z wodą</details><hr></p><p><details><summary>Klasyfikacja ZDR/ZZR:</summary><p>100 / 500 t (EUH014)</p></details></p><hr><p><details><summary>CAS:</summary><p>8014-95-7</p></details><hr><details><summary>Palność:</summary><p>Substancja niepalna</p></details>";
}

function substAmoniak() {
    var sAmoniak = document.getElementById("substContent");
    sAmoniak.innerHTML = "<p></p><h3>Amoniak</h3><details><summary>Zwroty bezpieczeństwa:</summary><p>Flam. Gas 2; H221 - gaz łatwopalny</p><p>Acute Tox. 3; H331 - działa toksycznie w następstwie wdychania</p><p>Skin Corr. 1B; H314 - powoduje powazne oparzenia skóry i uszkodzenie oczu</p><p>Aquatic Acute 1; H400 - działa bardzo toksycznie na organizmy wodne</p></details><hr></p><p><details><summary>Klasyfikacja ZDR/ZZR:</summary><p>50 / 200 t (nazwa)</p></details></p><hr><p><details><summary>CAS:</summary><p>7664-41-7</p></details><hr><details><summary>Palność:</summary><p>Materiał, który musi być podgrzany zanim ulegnie samozapłonowi. Woda może spowodować spienienie substancji jeśli przedostanie się pod powierzchnię cieczy i wydostanie ze strumieniem wypływającym jednakże wodna mgła nadaje się do użycia na powierzchni do ugaszenia pożaru</p></details><details><summary>Sposób gaszenia wg NFPA 325M:</summary><p>Raczej starać się zatrzymać wypływ gazu niż gasić. Jest niebezpieczne próbować gasić płomień ponieważ może się stworzyć mieszania wybuchowa. Można użyć CO<sub>2</sub> aby dojść do zaworu odcinającego. Zaleca się utrzymać płomień i schładzać otoczenie.</p></details><details><summary>Sposób postępowania w razie pożaru lub wubuchu:</summary><p><u>Środki gaśnicze</u>: Proszki gaśnicze, dwutlenek węgla, woda, piany średnie</p><p><u>Mały pożar</u>: gasić gaśnicami proszkowymi lub śniegowymi Użyć środków suchych gaśniczych albo CO<sub>2</sub>.</p><p><u>Duży pożar</u>: Proszki gaśnicze, piana, prądy wody rozproszone. Zbiorniki i butle narażone na działanie ognia lub wysokiej temperatury chłodzić woda z bezpiecznej odległości (groźba wybuchu) do czasu ugaszenia pożaru lub o ile to możliwe usunąć z zagrożonego obszaru. Woda nie może dostać się do wnętrza zbiornika.</p></details>";
}

function substAzotan() {
    var sAzotan = document.getElementById("substContent");
    sAzotan.innerHTML = "<p></p><h3>Azotan amonu (stop 93-97%)</h3><details><summary>Zwroty bezpieczeństwa:</summary><p>Skin Irrit. 2; H15 - działa drażniąco na skórę</p><p>Eye Irrit. 2; H319 - działa drażniąco na oczy</p><p>Ox. Liq. 2 / Ox. Sol. 2; H272 - może intensyfikować pożar, utleniacz</p></details><hr></p><p><details><summary>Klasyfikacja ZDR/ZZR:</summary><p>Stop azotanu amonu – Azotan amonu jako określona substancja wymieniony jest w tabeli nr 2 Rozporządzenia (objaśnienie 15):<br>„(...) odnosi się do azotanu amonu technicznego. <br>Niniejsze objaśnienie ma zastosowanie do:</p><ol style=\"list-style-type: lower-alpha;\"><li>azotanu amonu i mieszanin, w których zawartość azotu pochodząca z azotanu amonu(...):<br>− wynosi nie mniej niż 24,5 % i nie więcej niż 28 % i które zawierają nie więcej niż 0,4 % substancji palnych,<br>− jest większa niż 28 % i które zawierają nie więcej niż 0,2 % substancji palnych,</li><li>wodnych roztworów azotanu amonu, w których stężenie azotanu amonu jest większe niż 80 %”</li></ol><p> Definicji tej odpowiada kryterium ilościowe 350 / 2500 t.</p></details></p><hr><p><details><summary>CAS:</summary><p>6484-52-2</p></details><hr><details><summary>Palność:</summary><p>Substancja niepalna</p></details><details><summary>Sposób postępowania w razie pożaru lub wubuchu:</summary><p>W przypadku pożaru z udziałem azotanu amonu, roztwór musi być intensywnie chłodzony poprzez zraszanie wodą. Jeżeli to możliwe, usunąć go ze strefy ognia. Ratownicy powinni stosować odpowiednią ochronę dróg oddechowych ponieważ azotan amonu może rozkładać się do tlenków azotu i amoniaku.</p><p>Jedynym skutecznym sposobem przerwania rozkładu lub pożaru jest stosowanie dużej ilości wody (prądy rozproszone) spełniającej rolę czynnika chłodzącego i rozpuszczającego. Inne środki gaśnicze są mniej skuteczne. </p><p>Podczas pożaru i nagrzewania mogą powstawać toksyczne: NH<sub>3</sub>, NO<sub>x</sub>, CO<sub>2</sub>.</p></details>";
}

function substNawozy() {
    var sNawozy = document.getElementById("substContent");
    sNawozy.innerHTML = "<p></p><h3>Nawozy saletrzane</h3><details><summary>Zwroty bezpieczeństwa:</summary><p>Eye Irrit. 2; H319 - działa drażniąco na oczy</p></details><hr></p><p><details><summary>Klasyfikacja ZDR/ZZR:</summary>Dyrektywa Seveso III (2012/18/UE), której uregulowania zostały m. in. wdrożone w Rozporządzeniu Ministra Roz- woju z dnia 29 stycznia 2016 r. (Dz. U. 2016, poz. 138) podaje kryteria klasyfikacji zakładów o zwiększonym ryzyku (ZZR) lub dużym ryzyku (ZDR) wystąpienia poważnej awarii przemysłowej.</p><p>Zgodnie z powyższym Rozporządzeniem przypisano następujące wielkości progowe:</p><p>Saletrosan 30 – Azotan amonu jako określona substancja wymieniony jest w tabeli nr 2 Rozporządzenia (objaśnienie 14):<br>„(...)odnosi się do azotanu amonu stosowanego jako nawóz. Niniejsze określenie ma zastosowanie do prostych nawozów mineralnych opartych na azotanie amonu oraz do nawozów mineralnych wieloskładnikowych, w których zawartość azotu pochodząca z azotanu amonu wyrażona ułamkiem masowym, w procentach, jest większa niż:</p><ol style=\"list-style-type: lower-alpha;\"><li>24,5 % z wyjątkiem mieszanin prostych nawozów mineralnych opartych na azotanie amonu z dolomitem, kamieniem wapiennym lub węglanem wapnia o czystości co najmniej 90 %</li><li>15,75 % w mieszankach azotanu amonu i siarczanu(VI) amonu</li><li>28 % (28 % zawartości azotu pochodzącego z azotanu amonu odpowiada 80 % azotanowi amonu) w mieszaninach prostych nawozów mineralnych opartych na azotanie amonu z dolomitem, kamieniem wapiennym lub węglanem wapnia o czystości nie mniejszej niż 90 %</li> <p>– i które spełniają wymogi ust. 2 załącznika III do rozporządzenia nr 2003/2003”.</p><p>Definicji tej odpowiada kryterium ilościowe 1250 / 5000 t.</p></details></p><hr><p><details><summary>CAS:</summary><p>brak (mieszanina)</p></details><hr><details><summary>Palność:</summary><p>Substancja niepalna</p></details><details><summary>Sposób postępowania w razie pożaru lub wubuchu:</summary><p>W przypadku pożaru, nawóz musi być intensywnie chłodzony przez zraszanie wodą.</p><p><u>Środki gaśnicze</u>: jedynym skutecznym sposobem przerwania rozkładu lub pożaru jest stosowanie dużej ilości wody spełniającej rolę czynnika chłodzącego i rozpuszczającego. </p><p><u>Niewłaściwe środki gaśnicze</u>: nie stosować zwartych strumieni wody na powierzchnię palącej się substancji. Nie stosować CO<sub>2</sub>, piany gaśniczej, proszków gaśniczych.</p></details>";
}

function substFormalina() {
    var sFormalina = document.getElementById("substContent");
    sFormalina.innerHTML = "<p></p><h3>Formalina (36-50%)</h3><details><summary>Zwroty bezpieczeństwa:</summary><p>Acute Tox. 3; H301, H311, H331 - działa toksycznie po połknięciu, działa toksycznie w następstwie wdychania</p><p>Skin Sens. 1; H317 – może powodować reakcję alergiczną skóry</p><p> Carc. 1B; H350 - może powodować raka</p><p>STOT SE 2; H371 - może powodować uszkodzenie narządów</p><p>Muta. 2; H341 - podejrzewa się, że powoduje wady genetyczne</p></details><hr></p><p><details><summary>Klasyfikacja ZDR/ZZR:</summary><p>50 / 200 t (H331)</p></details></p><hr><p><details><summary>CAS:</summary><p>50-00-0</p></details><hr><details><summary>Palność:</summary><p>Materiały, które muszą być umiarkowanie podgrzane, aby nastąpił zapłon. Do gaszenia pożaru można użyć rozpylonej wody, ponieważ można ochłodzić materiał poniżej jego temperatury zapłonu.</p></details><details><summary>Sposób postępowania w razie pożaru lub wubuchu:</summary><p><u>Mały pożar</u> – palącego gazu nie gasić – pozwolić się wypalić. Palące się roztwory gasić gaśnicą proszkową lub śniegową (dwutlenek węgla).</p><p><u>Duży pożar</u> – palące się zbiorniki lub rozlewiska gasić pianą lub prądami wodnymi rozproszonymi, nie stosować zwartych strumieni wody na powierzchnie cieczy. Zbiorniki narażone na działanie ognia lub wysokiej temperatury chłodzić wodą z bezpiecznej odległości, jeśli to możliwe, usunąć je z obszaru zagrożenia (groźba wybuchu).</p></details>";
}

function substMetanol() {
    var sMetanol = document.getElementById("substContent");
    sMetanol.innerHTML = "<p></p><h3>Metanol</h3><details><summary>Zwroty bezpieczeństwa:</summary><p>Flam. Liq. 2; H225 - wysoce łatwopalna ciecz i pary</p><p>Acute Tox. 3; H301, H311, H331 - działa toksycznie po połknięciu, działa toksycznie w następstwie wdychania</p><p>STOT SE 1; H370 – powoduje uszkodzenie narządów</p></details><hr></p><p><details><summary>Klasyfikacja ZDR/ZZR:</summary><p>500 / 5000 t (nazwa)</p></details></p><hr><p><details><summary>CAS:</summary><p>67-56-1</p></details><hr><details><summary>Palność:</summary><p>Gazy łatwopalne lub bardzo lotne ciecze łatwopalne.</p></details><details><summary>Sposób postępowania w razie pożaru lub wubuchu:</summary><p><u>Mały pożar</u> – palącego gazu nie gasić – pozwolić się wypalić. Palące się roztwory gasić gaśnicą proszkową lub śniegową (dwutlenek węgla).</p><p><u>Duży pożar</u> – palące się zbiorniki lub rozlewiska gasić pianą lub prądami wodnymi rozproszonymi, nie stosować zwartych strumieni wody na powierzchnie cieczy. Zbiorniki narażone na działanie ognia lub wysokiej temperatury chłodzić wodą z bezpiecznej odległości, jeśli to możliwe, usunąć je z obszaru zagrożenia (groźba wybuchu).</p></details>";
}

function substTrioksan() {
    var sTrioksan = document.getElementById("substContent");
    sTrioksan.innerHTML = "<p></p><h3>Trioksan</h3><details><summary>Zwroty bezpieczeństwa:</summary><p>Flam. Sol. 1; H228 - substancja stała łatwopalna</p><p>STOT SE 3; H335 – może powodować podrażnienie dróg oddechowych</p><p>Repr. 2; H361d - podejrzewa się, że działa szkodliwie na dziecko w łonie matki</details><hr></p><p><details><summary>Klasyfikacja ZDR/ZZR:</summary><p> - </p></details></p><hr><p><details><summary>CAS:</summary><p>110-88-3</p></details><hr><details><summary>Palność:</summary><p>Łatwopalne ciało stałe</p></details><details><summary>Sposób postępowania w razie pożaru lub wubuchu:</summary><p>Do gaszenia pożarów należy stosować następujące środki gaśnicze:, proszki gaśnicze, CO<sub>2<sub>, piana. Nie ma ograniczeń dla środków gaszących.</p><p>W razie pożaru możliwe powstawanie niebezpiecznych palnych gazów lub par. Pary są cięższe od powietrza i mogą zalegać przy powierzchni gruntu.</p><p>W podwyższonej temperaturze tworzy wybuchowe mieszaniny z powietrzem.</p><p>Ogień może spowodować wydzielanie pary formaldehydu. Należy używać aparaty tlenowe. Tłumić pary rozpylonym strumieniem wody.</p></details>";
}

function substMrowczan() {
    var sMrowczan = document.getElementById("substContent");
    sMrowczan.innerHTML = "<p></p><h3>Mrówczan metylu</h3><details><summary>Zwroty bezpieczeństwa:</summary><p>Flam. Liq. 1; H224 - skrajnie łatwopalna ciecz i pary</p><p>Acute Tox. 4; H302, H332 - działa szkodliwie po połknięciu i w następstwie wdychania</p><p>Eye Irrit. 2; H319 – działa drażniąco na oczy</p><p>STOT SE 3; H335 - może powodować porażnienia dróg oddechowych</p></details><hr></p><p><details><summary>Klasyfikacja ZDR/ZZR:</summary><p>10 / 50 t (H224)</p></details></p><hr><details><summary>CAS:</summary><p>107-31-3</p></details><hr><details><summary>Palność:</summary><p>Materiały, które mogą ulec zapłonowi w niemal wszystkich normalnych warunkach temperaturowych. Ze względu na niską temperaturę zapłonu woda może być nieskuteczna.</p></details><details><summary>Sposób postępowania w razie pożaru lub wubuchu:</summary><p>Do gaszenia pożarów należy stosować następujące środki gaśnicze:, proszki gaśnicze, CO<sub>2</sub>, piana.</p><p>Tworzy wybuchowe mieszaniny z powietrzem.</p><p>Stosować gazoszczelną odzież i indywidualny aparat do oddychania.</p><p>Zapobiegać wyładowaniom elektrycznym.</p><p>Nie dopuścić do przedostania się wody do wód powierzchniowych lub gruntowych.</p></details>";
}

function substAzotyn() {
    var sAzotyn = document.getElementById("substContent");
    sAzotyn.innerHTML = "<p></p><h3>Azotyn amonu (20%)</h3><details><summary>Zwroty bezpieczeństwa:</summary><p>Flam. Liq. 1; H224 - skrajnie łatwopalna ciecz i pary</p><p>Acute Tox. 4; H302 - działa szkodliwie po połknięciu </p></details><hr><details><summary>Klasyfikacja ZDR/ZZR:</summary><p> - </p></details></p><hr><details><summary>CAS:</summary><p>13446-48-5</p></details><hr><details><summary>Palność:</summary><p>Niepalny</p></details><details><summary>Warunki, których należy unikać:</summary><p>Nie dopuścić do zakwaszania roztworu tlenkami azotu – w trakcie absorpcji tlenków w roztworze w wieżach produkcyjnych musi być zapewniony stały dopływ świeżego roztworu węglanu amonu.</p><p>Nie można dopuścić do wzrostu temperatury roztworu powyżej 28<sup>o</sup>C (blokadowy parametr na instalacji) ponieważ może to skutkować wybuchowym rozkładem roztworu.</p></details>";
}

function substSha() {
    var sSha = document.getElementById("substContent");
    sSha.innerHTML = "<p></p><h3>Siarczan hydroksyloaminy (15%)</h3><details><summary>Zwroty bezpieczeństwa:</summary><p>Met. Corr. 1; H290 - może powodować korozję metali</p><p>Carc. 2; H351 - podejrzewa się, że powoduje raka</p><p>Skin Irrit. 2; H315 – działa drażniąco na skórę</p><p>Skin Sens. 1; H317 - może powodować reakcję alergiczną skóry</p><p>Eye Irrit. 2; H319 - działa drażniąco na oczy</p><p>Aquatic Chronic 2; H411 - działa toksycznie na organizmy wodne, powodując długotrwałe skutki</p></details><hr></p><p><details><summary>Klasyfikacja ZDR/ZZR:</summary><p>200 / 500 t (jako roztwór, H411)</p></details></p><hr><details><summary>CAS:</summary><p>10039-54-0</p></details><hr><details><summary>Palność:</summary><p>Niepalny</p></details>";
}
